using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml.Linq;

namespace Atomic_WinUI
{
    public static class ElementData
    {
        public static List<Element> Elements = new List<Element>
        {
            // Example elements
            new Element { OriginalName = "Hydrogen", Symbol = "H", AtomicNumber = 1 },
            new Element { OriginalName = "Helium", Symbol = "He", AtomicNumber = 2 },
            new Element { OriginalName = "Lithium", Symbol = "Li", AtomicNumber = 3 },
            new Element { OriginalName = "Beryllium", Symbol = "Be", AtomicNumber = 4 },
            new Element { OriginalName = "Boron", Symbol = "B", AtomicNumber = 5 },
            new Element { OriginalName = "Carbon", Symbol = "C", AtomicNumber = 6 },
            new Element { OriginalName = "Nitrogen", Symbol = "N", AtomicNumber = 7 },
            new Element { OriginalName = "Oxygen", Symbol = "O", AtomicNumber = 8 },
            new Element { OriginalName = "Fluorine", Symbol = "F", AtomicNumber = 9 },
            new Element { OriginalName = "Neon", Symbol = "Ne", AtomicNumber = 10 },
            new Element { OriginalName = "Sodium", Symbol = "Na", AtomicNumber = 11 },
            new Element { OriginalName = "Magnesium", Symbol = "Mg", AtomicNumber = 12 },
            new Element { OriginalName = "Aluminium", Symbol = "Al", AtomicNumber = 13 },
            new Element { OriginalName = "Silicon", Symbol = "Si", AtomicNumber = 14 },
            new Element { OriginalName = "Phosphorus", Symbol = "P", AtomicNumber = 15 },
            new Element { OriginalName = "Sulfur", Symbol = "S", AtomicNumber = 16 },
            new Element { OriginalName = "Chlorine", Symbol = "Cl", AtomicNumber = 17 },
            new Element { OriginalName = "Argon", Symbol = "Ar", AtomicNumber = 18 },
            new Element { OriginalName = "Potassium", Symbol = "K", AtomicNumber = 19 },
            new Element { OriginalName = "Calcium", Symbol = "Ca", AtomicNumber = 20 },
            new Element { OriginalName = "Scandium", Symbol = "Sc", AtomicNumber = 21 },
            new Element { OriginalName = "Titanium", Symbol = "Ti", AtomicNumber = 22 },
            new Element { OriginalName = "Vanadium", Symbol = "V", AtomicNumber = 23 },
            new Element { OriginalName = "Chromium", Symbol = "Cr", AtomicNumber = 24 },
            new Element { OriginalName = "Manganese", Symbol = "Mn", AtomicNumber = 25 },
            new Element { OriginalName = "Iron", Symbol = "Fe", AtomicNumber = 26 },
            new Element { OriginalName = "Cobalt", Symbol = "Co", AtomicNumber = 27 },
            new Element { OriginalName = "Nickel", Symbol = "Ni", AtomicNumber = 28 },
            new Element { OriginalName = "Copper", Symbol = "Cu", AtomicNumber = 29 },
            new Element { OriginalName = "Zinc", Symbol = "Zn", AtomicNumber = 30 },
            new Element { OriginalName = "Gallium", Symbol = "Ga", AtomicNumber = 31 },
            new Element { OriginalName = "Germanium", Symbol = "Ge", AtomicNumber = 32 },
            new Element { OriginalName = "Arsenic", Symbol = "As", AtomicNumber = 33 },
            new Element { OriginalName = "Selenium", Symbol = "Se", AtomicNumber = 34 },
            new Element { OriginalName = "Bromine", Symbol = "Br", AtomicNumber = 35 },
            new Element { OriginalName = "Krypton", Symbol = "Kr", AtomicNumber = 36 },
            new Element { OriginalName = "Rubidium", Symbol = "Rb", AtomicNumber = 37 },
            new Element { OriginalName = "Strontium", Symbol = "Sr", AtomicNumber = 38 },
            new Element { OriginalName = "Yttrium", Symbol = "Y", AtomicNumber = 39 },
            new Element { OriginalName = "Zirconium", Symbol = "Zr", AtomicNumber = 40 },
            new Element { OriginalName = "Niobium", Symbol = "Nb", AtomicNumber = 41 },
            new Element { OriginalName = "Molybdenum", Symbol = "Mo", AtomicNumber = 42 },
            new Element { OriginalName = "Technetium", Symbol = "Tc", AtomicNumber = 43 },
            new Element { OriginalName = "Ruthenium", Symbol = "Ru", AtomicNumber = 44 },
            new Element { OriginalName = "Rhodium", Symbol = "Rh", AtomicNumber = 45 },
            new Element { OriginalName = "Palladium", Symbol = "Pd", AtomicNumber = 46 },
            new Element { OriginalName = "Silver", Symbol = "Ag", AtomicNumber = 47 },
            new Element { OriginalName = "Cadmium", Symbol = "Cd", AtomicNumber = 48 },
            new Element { OriginalName = "Indium", Symbol = "In", AtomicNumber = 49 },
            new Element { OriginalName = "Tin", Symbol = "Sn", AtomicNumber = 50 },
            new Element { OriginalName = "Antimony", Symbol = "Sb", AtomicNumber = 51 },
            new Element { OriginalName = "Tellurium", Symbol = "Te", AtomicNumber = 52 },
            new Element { OriginalName = "Iodine", Symbol = "I", AtomicNumber = 53 },
            new Element { OriginalName = "Xenon", Symbol = "Xe", AtomicNumber = 54 },
            new Element { OriginalName = "Cesium", Symbol = "Cs", AtomicNumber = 55 },
            new Element { OriginalName = "Barium", Symbol = "Ba", AtomicNumber = 56 },
            new Element { OriginalName = "Lanthanum", Symbol = "La", AtomicNumber = 57 },
            new Element { OriginalName = "Cerium", Symbol = "Ce", AtomicNumber = 58 },
            new Element { OriginalName = "Praseodymium", Symbol = "Pr", AtomicNumber = 59 },
            new Element { OriginalName = "Neodymium", Symbol = "Nd", AtomicNumber = 60 },
            new Element { OriginalName = "Promethium", Symbol = "Pm", AtomicNumber = 61 },
            new Element { OriginalName = "Samarium", Symbol = "Sm", AtomicNumber = 62 },
            new Element { OriginalName = "Europium", Symbol = "Eu", AtomicNumber = 63 },
            new Element { OriginalName = "Gadolinium", Symbol = "Gd", AtomicNumber = 64 },
            new Element { OriginalName = "Terbium", Symbol = "Tb", AtomicNumber = 65 },
            new Element { OriginalName = "Dysprosium", Symbol = "Dy", AtomicNumber = 66 },
            new Element { OriginalName = "Holmium", Symbol = "Ho", AtomicNumber = 67 },
            new Element { OriginalName = "Erbium", Symbol = "Er", AtomicNumber = 68 },
            new Element { OriginalName = "Thulium", Symbol = "Tm", AtomicNumber = 69 },
            new Element { OriginalName = "Ytterbium", Symbol = "Yb", AtomicNumber = 70 },
            new Element { OriginalName = "Lutetium", Symbol = "Lu", AtomicNumber = 71 },
            new Element { OriginalName = "Hafnium", Symbol = "Hf", AtomicNumber = 72 },
            new Element { OriginalName = "Tantalum", Symbol = "Ta", AtomicNumber = 73 },
            new Element { OriginalName = "Tungsten", Symbol = "W", AtomicNumber = 74 },
            new Element { OriginalName = "Rhenium", Symbol = "Re", AtomicNumber = 75 },
            new Element { OriginalName = "Osmium", Symbol = "Os", AtomicNumber = 76 },
            new Element { OriginalName = "Iridium", Symbol = "Ir", AtomicNumber = 77 },
            new Element { OriginalName = "Platinum", Symbol = "Pt", AtomicNumber = 78 },
            new Element { OriginalName = "Gold", Symbol = "Au", AtomicNumber = 79 },
            new Element { OriginalName = "Mercury", Symbol = "Hg", AtomicNumber = 80 },
            new Element { OriginalName = "Thallium", Symbol = "Tl", AtomicNumber = 81 },
            new Element { OriginalName = "Lead", Symbol = "Pb", AtomicNumber = 82 },
            new Element { OriginalName = "Bismuth", Symbol = "Bi", AtomicNumber = 83 },
            new Element { OriginalName = "Polonium", Symbol = "Po", AtomicNumber = 84 },
            new Element { OriginalName = "Astatine", Symbol = "At", AtomicNumber = 85 },
            new Element { OriginalName = "Radon", Symbol = "Rn", AtomicNumber = 86 },
            new Element { OriginalName = "Francium", Symbol = "Fr", AtomicNumber = 87 },
            new Element { OriginalName = "Radium", Symbol = "Ra", AtomicNumber = 88 },
            new Element { OriginalName = "Actinium", Symbol = "Ac", AtomicNumber = 89 },
            new Element { OriginalName = "Thorium", Symbol = "Th", AtomicNumber = 90 },
            new Element { OriginalName = "Protactinium", Symbol = "Pa", AtomicNumber = 91 },
            new Element { OriginalName = "Uranium", Symbol = "U", AtomicNumber = 92 },
            new Element { OriginalName = "Neptunium", Symbol = "Np", AtomicNumber = 93 },
            new Element { OriginalName = "Plutonium", Symbol = "Pu", AtomicNumber = 94 },
            new Element { OriginalName = "Americium", Symbol = "Am", AtomicNumber = 95 },
            new Element { OriginalName = "Curium", Symbol = "Cm", AtomicNumber = 96 },
            new Element { OriginalName = "Berkelium", Symbol = "Bk", AtomicNumber = 97 },
            new Element { OriginalName = "Californium", Symbol = "Cf", AtomicNumber = 98 },
            new Element { OriginalName = "Einsteinium", Symbol = "Es", AtomicNumber = 99 },
            new Element { OriginalName = "Fermium", Symbol = "Fm", AtomicNumber = 100 },
            new Element { OriginalName = "Mendelevium", Symbol = "Md", AtomicNumber = 101 },
            new Element { OriginalName = "Nobelium", Symbol = "No", AtomicNumber = 102 },
            new Element { OriginalName = "Lawrencium", Symbol = "Lr", AtomicNumber = 103 },
            new Element { OriginalName = "Rutherfordium", Symbol = "Rf", AtomicNumber = 104 },
            new Element { OriginalName = "Dubnium", Symbol = "Db", AtomicNumber = 105 },
            new Element { OriginalName = "Seaborgium", Symbol = "Sg", AtomicNumber = 106 },
            new Element { OriginalName = "Bohrium", Symbol = "Bh", AtomicNumber = 107 },
            new Element { OriginalName = "Hassium", Symbol = "Hs", AtomicNumber = 108 },
            new Element { OriginalName = "Meitnerium", Symbol = "Mt", AtomicNumber = 109 },
            new Element { OriginalName = "Darmstadtium", Symbol = "Ds", AtomicNumber = 110 },
            new Element { OriginalName = "Roentgenium", Symbol = "Rg", AtomicNumber = 111 },
            new Element { OriginalName = "Copernicium", Symbol = "Cn", AtomicNumber = 112 },
            new Element { OriginalName = "Nihonium", Symbol = "Nh", AtomicNumber = 113 },
            new Element { OriginalName = "Flerovium", Symbol = "Fl", AtomicNumber = 114 },
            new Element { OriginalName = "Moscovium", Symbol = "Mc", AtomicNumber = 115 },
            new Element { OriginalName = "Livermorium", Symbol = "Lv", AtomicNumber = 116 },
            new Element { OriginalName = "Tennessine", Symbol = "Ts", AtomicNumber = 117 },
            new Element { OriginalName = "Oganesson", Symbol = "Og", AtomicNumber = 118 },
        };

        public static Element GetElementByName(string name)
        {
            return Elements.FirstOrDefault(e => e.OriginalName.Equals(name, StringComparison.OrdinalIgnoreCase));
        }
    }
}